version: "2"
services:
  jenkins:
    image: jenkinsci/blueocean
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2376
      - DOCKER_OPTS="-H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock"
    user: root
    ports:
      - "8080:8080"
      - "8443:8443"
      - "50000:50000"
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
